export default {
    UPDATE_FECHA:"UPDATE_FECHA",

    GET_PROXIMOS_ESTRENOS:"GET_PROXIMOS_ESTRENOS",
    GET_PROXIMOS_ESTRENOS_FULFILLED:"GET_PROXIMOS_ESTRENOS_FULFILLED",
    GET_PROXIMOS_ESTRENOS_PENDING:"GET_PROXIMOS_ESTRENOS_PENDING",
    GET_PROXIMOS_ESTRENOS_REJECTED:"GET_PROXIMOS_ESTRENOS_REJECTED",
    

    GET_ESTRENOS:"GET_ESTRENOS",
    GET_ESTRENOS_PENDING:"GET_ESTRENOS_PENDING",
    GET_ESTRENOS_FULFILLED:"GET_ESTRENOS_FULFILLED",
    GET_ESTRENOS_REJECTED:"GET_ESTRENOS_REJECTED",

    //acciones para creditos:
    GET_CREDITOS:"GET_CREDITOS",
    GET_CREDITOS_FULFILLED:"GET_CREDITOS_FULFILLED",
    GET_CREDITOS_PENDING:"GET_CREDITOS_PENDING",
    GET_CREDITOS_REJECTED:"GET_CREDITOS_REJECTED",

    //acciones para detalles:
    GET_PELICULA_DETALLES:"GET_PELICULA_DETALLES",
    GET_PELICULA_DETALLES_FULFILLED:"GET_PELICULA_DETALLES_FULFILLED",
    GET_PELICULA_DETALLES_PENDING:"GET_PELICULA_DETALLES_PENDING",
    GET_PELICULA_DETALLES_REJECTED:"GET_PELICULA_DETALLES_REJECTED"
}